# Generated by Django 5.2.7 on 2026-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0002_rename_status_cliente_status_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='saldo_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
