# Generated by Django 5.2.7 on 2026-05-09 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0003_divida_saldo_restante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
