# Generated by Django 5.2.7 on 2026-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0004_alter_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
