# Generated by Django 6.0.4 on 2026-06-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0004_alter_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divida',
            name='saldo_restante',
        ),
    ]
