# Generated by Django 5.2.7 on 2026-05-12 17:46

import antiveaco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0005_divida_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='data_vencimento',
            field=models.DateField(blank=True, default=antiveaco.models.calcular_vencimento_padrao, null=True),
        ),
    ]
