# Generated by Django 5.2.7 on 2026-07-06 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiveaco', '0006_alter_divida_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='data_divida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
